### ISSUE TITLE
http to https

### ISSUE THREAD

**Issue by brianrisk** [tradingjunkie/OctaveQuandlInterface#1]
Quandl will soon only accept API calls to https.  All urls with "http:" need to be updated to "https:".

Thank you for your help with this!  Let me know if you need any assistance.

**Comment by brianrisk** [comment]
It is unclear if Octave will work with https.  Do you know if this is the case?

**Comment by ifed-ucsd** [comment]
I'm not sure. Were you able to test the update?

**Comment by brianrisk** [comment]
@ifed-ucsd A user tested it and reported this:  _With the update I get "Code does not exist" errors. When I looked deeper I found that urlread() in api.m was returning error "Peer certificate cannot be authenticated with given CA certificates". I had a look around and could not find anybody who had got Octave working with https._

**Comment by ifed-ucsd** [comment]
Without having tested the code, here are my thoughts. Octave's urlread() is a wrapper for libcurl (https://www.gnu.org/software/octave/doc/interpreter/URL-Manipulation.html) which supports https (http://curl.haxx.se/libcurl/). Therefore, it should work, but I don't know for sure
